FROM public.ecr.aws/lambda/python:3.7

# Install the function's dependencies using file requirements.txt
# from your project folder.
RUN yum install -y gcc
# Install required dependencies

    
RUN yum install -y wget zip && \
    yum clean all && \
    rm -rf /var/cache/yum

# Install libsndfile
RUN wget http://www.mega-nerd.com/libsndfile/files/libsndfile-1.0.28.tar.gz && \
    tar -xzf libsndfile-1.0.28.tar.gz && \
    cd libsndfile-1.0.28 && \
    ./configure --prefix=/usr/local --disable-static && \
    make && \
    make install

ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
ENV NUMBA_CACHE_DIR=/tmp/



COPY requirements.txt  .
RUN  pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY . ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler (could also be done as a parameter override outside of the Dockerfile)
CMD [ "app.handler" ]